use_frameworks!

#platform :ios, '10.0'

target 'GQPaymentIOSSDK_Example' do

  pod 'CashfreePG', '~> 2.0.3'
  pod 'razorpay-pod', '1.2.5'
  pod 'GQPaymentIOSSDK', :path => '../'

  target 'GQPaymentIOSSDK_Tests' do
    inherit! :search_paths

    
  end
end
